server:
  port: 9999

spring:
#  debug: true
  application:
    name: blog-posts
  datasource:
    url: jdbc:postgresql://flora.db.elephantsql.com:5432/lsggevzp
    username: lsggevzp
    password: QLxGtPlnTE2fMV0sbe9_6TRcBm_uPSI4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  reactor:
    debug-agent:
      enabled: true


#      datasource:
#        url: jdbc:postgresql://dpg-cknqtcujmi5c73e0i3n0-a.oregon-postgres.render.com/blogpost_we86
#        username: badmus
#        password: ryYKcjTYsO1bWG6W4dF1WpToGjAiUQFX